#!/bin/bash
#
# Reject force pushes to branches matching a certain pattern,
# as well as deletion of such branches.
#
# Based on https://github.com/olshanov/git-hooks/blob/master/pre-receive.deny-force-push-to-branches
#
# See `man githooks` for parameters specification

# master OR 3-4 digits with an optional 'refs/heads/' prefix
PROTECTED="^(refs/heads/)?[0-9]{3,4}$|^master$"

# special revision indicating branch creation or deletion: it is 40 zeros, as stated in `man githooks`
ZERO="0000000000000000000000000000000000000000"

# git push can trigger update of several references at once
# they are handled in a loop one-by-one
while read oldrev newrev refname
do
  # newrev  - the new object name to be stored in the ref.
  # oldrev  - the old object name stored in the ref,
  # refname - the name of the ref being updated,

  # create new branch => no further checking needed
  if [[ $oldrev == $ZERO ]]; then
    continue;
  fi  

  if [[ $refname =~ $PROTECTED ]] ; then
    # check if it is branch deletion
    if [[ $newrev == $ZERO ]]; then
      echo "*** Deleting a release or the master branch is not allowed" >&2
      exit 1
    else 
      # check if this is a fast-foward update (i.e. not a force push): it is when $oldrev is an ancestor of $newrev
      merge_base=$(git merge-base $oldrev $newrev)
      if [[ $oldrev != $merge_base ]]; then
        echo "*** Force push to a release or to the master branch is not allowed" >&2
        exit 1
      fi
    fi
  fi
done

exit 0
